#
# This file contains configuration variables to customize your site.
# Variables are accessed using the convention:  site.<variable_name>
# Example:
#     {{ site.name }} will print the value of name:
#
# YAML Syntax: http://en.wikipedia.org/wiki/YAML#Syntax

# Name of your site (Used in meta data and throughout site branding)
name: "Uncoded"

# Short bio or description (displayed in the <header> section)
description: "We are open, technologists, community driven.<br />We are <em>Uncoded</em>, Long Beach"

# Your website URL (e.g. http://username.github.io or http://www.yourdomain.foo)
# Used for Sitemap.xml and your RSS feed
url: http://www.uncoded.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://username.github.io/repository-name)
# and NOT your User repository (http://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Customize menu names & links for the site
navigation: # Site Navigation Menu elements: names and links
  brand:
    text: "<span class='light'>uncoded</span>"
    link: "#page-top"
    logo: "" # if empty, defaults to an arrow icon using font-awesome
  main: # Main Menu  ( "LABEL": "URL" )
    "Vision": "#vision"
    "Initiatives": "#initiatives"
    "Learn More": "#learn_more"
    "Get Involved": "#get_involved"
    "Forum": "/forum"
  foot: # Footer Menu
    "Copyright &copy; 2015 Uncoded.org":

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/12898756

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
links:
  dribbble:
  email: "uncodedlb@gmail.com"
  facebook: "groups/uncoded"
  flickr:
  github: "uncodedlb"
  instagram: "uncodedlb"
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: "uncodedlb"
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  irc:
    nick: kiwi_uncodedlb
    channels: "#jekyll,#sculpin,#css,#sass,#less,#atom,#node.js,#io.js,#drupal,#nginx,#uncodedlb"

# Your disqus shortname, entering this will enable commenting on posts
disqus:

# http://www.discourse.org/
# Setup://blog.discourse.org/2014/04/install-discourse-in-under-30-minutes/
# Based on http://eviltrout.com/2014/01/22/embedding-discourse.html
discourse:
  enabled: true
  url: "http://discourse.uncoded.org/" #discourseUrl - points to the root URL of your Discourse forum.
  # Make sure discourseEmbedUrl is the canonical URL to the page where you are embedding Discourse. You will want to make sure this uniquely identifies the page. For my blog template, I use the following code to link to the article: discourseEmbedUrl = 'http://eviltrout.com<%= current_page.url %>'

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "UA-60220524-3"

#
# !! You don't need to change any of the configuration flags below !!
#

styling: "/style.css"
script: "/js/rockon.js"
fontawesome: "/font-awesome/css/font-awesome.min.css"
jquery:
  main: "/js/jquery.js"
  easing: "/js/jquery.easing.min.js"
lodash:
  js: "/js/lodash.js"
bootstrap:
  css: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"  # "css/bootstrap.min.css"
  js: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"     # "js/bootstrap.min.js"
googlefonts: "http://fonts.googleapis.com/css?family=Montserrat:400,700|Lora:400,700,400italic,700italic"
googlemaps: "https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false" # - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/


markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
#version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .gitignore
  - .editorconfig
